namespace Messenger.Domain.Channels.Permissions;

[Flags]
public enum ChannelPermission : ulong
{
    SEND_MESSAGES = 1 << 0,
    ATTACH_FILES = 1 << 1,
    USE_REACTIONS = 1 << 2,
    USE_VOICE_MESSAGES = 1 << 3,
    PIN_MESSAGES = 1 << 4,
    MENTION_EVERYONE = 1 << 5,
    MANAGE_MEMBERS = 1 << 6,
    MANAGE_CHANNEL = 1 << 7,
    AUDIT_LOG_VIEW = 1 << 8,
    CREATE_POLLS = 1 << 9,
    MANAGE_MESSAGES = 1 << 10,

    DM_CHANNEL = SEND_MESSAGES | ATTACH_FILES | USE_REACTIONS
        | USE_VOICE_MESSAGES | PIN_MESSAGES | MENTION_EVERYONE,

    DEFAULT_DM_GROUP_MEMBER = SEND_MESSAGES | ATTACH_FILES | USE_REACTIONS
        | USE_VOICE_MESSAGES | PIN_MESSAGES | MENTION_EVERYONE
        | MANAGE_MEMBERS | MANAGE_CHANNEL | CREATE_POLLS,

    OWNER = ulong.MaxValue,
}
