namespace MessengerAPI.Domain.Channels;

[Flags]
public enum ChannelPermissions : ulong
{
    SEND_MESSAGES = 1 << 1,
    ATTACH_FILES = 1 << 2,
    USE_REACTIONS = 1 << 3,
    USE_VOICE_MESSAGES = 1 << 4,
    PIN_MESSAGES = 1 << 5,
    MENTION_EVERYONE = 1 << 6,
    MANAGE_MEMBERS = 1 << 7,
    MANAGE_CHANNEL = 1 << 8,
    AUDIT_LOG_VIEW = 1 << 9,
    CREATE_POLLS = 1 << 10,

    PRIVATE_CHANNEL = SEND_MESSAGES | ATTACH_FILES | USE_REACTIONS
           | USE_VOICE_MESSAGES | PIN_MESSAGES | MENTION_EVERYONE,

    DEFAULT_MEMBER = SEND_MESSAGES | ATTACH_FILES | USE_REACTIONS
           | USE_VOICE_MESSAGES | PIN_MESSAGES | MENTION_EVERYONE
           | MANAGE_MEMBERS | MANAGE_CHANNEL | CREATE_POLLS,

    OWNER = ulong.MaxValue,
}
