receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "scylladb"
          static_configs:
            - targets: ["scylla:9180"]

exporters:
  otlp/grafana-cloud:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
    protocol: ${env:OTEL_EXPORTER_OTLP_PROTOCOL}
    headers: ${env:OTEL_EXPORTER_OTLP_HEADERS}

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlp/grafana-cloud]
