// <auto-generated />
using System;
using MessengerAPI.Infrastructure.Common.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessengerAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240915154403_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChannelUser", b =>
                {
                    b.Property<Guid>("ChannelsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("uuid");

                    b.HasKey("ChannelsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("ChannelUser");
                });

            modelBuilder.Entity("MessageAttachments", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FileDataId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId", "FileDataId");

                    b.HasIndex("FileDataId");

                    b.ToTable("MessageAttachments");
                });

            modelBuilder.Entity("MessengerAPI.Domain.ChannelAggregate.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<long?>("LastMessageId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("LastMessageId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("MessengerAPI.Domain.ChannelAggregate.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ReplyTo")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("MessengerAPI.Domain.Common.Entities.FileData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MessengerAPI.Domain.Common.Entities.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactionGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReactionGroupId");

                    b.ToTable("Reaction");
                });

            modelBuilder.Entity("MessengerAPI.Domain.Common.Entities.ReactionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReactionGroups");
                });

            modelBuilder.Entity("MessengerAPI.Domain.UserAggregate.Entities.ProfilePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ProfilePhoto");
                });

            modelBuilder.Entity("MessengerAPI.Domain.UserAggregate.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MessengerAPI.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GlobalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PasswordUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TerminateSessions")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorAuthentication")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UsernameUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChannelUser", b =>
                {
                    b.HasOne("MessengerAPI.Domain.ChannelAggregate.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerAPI.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MessageAttachments", b =>
                {
                    b.HasOne("MessengerAPI.Domain.Common.Entities.FileData", null)
                        .WithMany()
                        .HasForeignKey("FileDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerAPI.Domain.ChannelAggregate.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MessengerAPI.Domain.ChannelAggregate.Channel", b =>
                {
                    b.HasOne("MessengerAPI.Domain.Common.Entities.FileData", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("MessengerAPI.Domain.ChannelAggregate.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("LastMessageId");

                    b.HasOne("MessengerAPI.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.OwnsMany("MessengerAPI.Domain.ChannelAggregate.ValueObjects.AdminId", "AdminIds", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("UserId");

                            b1.Property<Guid>("ChannelId")
                                .HasColumnType("uuid");

                            b1.HasKey("UserId", "ChannelId");

                            b1.HasIndex("ChannelId");

                            b1.ToTable("ChannelAdminIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChannelId");

                            b1.HasOne("MessengerAPI.Domain.UserAggregate.User", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsMany("MessengerAPI.Domain.ChannelAggregate.ValueObjects.PinnedMessageId", "PinnedMessageIds", b1 =>
                        {
                            b1.Property<long>("MessageId")
                                .HasColumnType("bigint")
                                .HasColumnName("MessageId");

                            b1.Property<Guid>("ChannelId")
                                .HasColumnType("uuid");

                            b1.HasKey("MessageId", "ChannelId");

                            b1.HasIndex("ChannelId");

                            b1.ToTable("PinnedMessageIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChannelId");

                            b1.HasOne("MessengerAPI.Domain.ChannelAggregate.Entities.Message", null)
                                .WithMany()
                                .HasForeignKey("MessageId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.Navigation("AdminIds");

                    b.Navigation("Image");

                    b.Navigation("PinnedMessageIds");
                });

            modelBuilder.Entity("MessengerAPI.Domain.ChannelAggregate.Entities.Message", b =>
                {
                    b.HasOne("MessengerAPI.Domain.ChannelAggregate.Channel", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerAPI.Domain.UserAggregate.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MessengerAPI.Domain.ChannelAggregate.ValueObjects.UserReaction", "Reactions", b1 =>
                        {
                            b1.Property<long>("MessageId")
                                .HasColumnType("bigint");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ReactionId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("MessageId", "UserId");

                            b1.HasIndex("ReactionId");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserReactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MessageId");

                            b1.HasOne("MessengerAPI.Domain.Common.Entities.Reaction", "Reaction")
                                .WithMany()
                                .HasForeignKey("ReactionId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("MessengerAPI.Domain.UserAggregate.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Reaction");

                            b1.Navigation("User");
                        });

                    b.Navigation("Reactions");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MessengerAPI.Domain.Common.Entities.FileData", b =>
                {
                    b.HasOne("MessengerAPI.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MessengerAPI.Domain.Common.Entities.Reaction", b =>
                {
                    b.HasOne("MessengerAPI.Domain.Common.Entities.ReactionGroup", null)
                        .WithMany("Reactions")
                        .HasForeignKey("ReactionGroupId");
                });

            modelBuilder.Entity("MessengerAPI.Domain.UserAggregate.Entities.ProfilePhoto", b =>
                {
                    b.HasOne("MessengerAPI.Domain.Common.Entities.FileData", "File")
                        .WithOne()
                        .HasForeignKey("MessengerAPI.Domain.UserAggregate.Entities.ProfilePhoto", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessengerAPI.Domain.UserAggregate.User", null)
                        .WithMany("ProfilePhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("MessengerAPI.Domain.UserAggregate.Entities.Session", b =>
                {
                    b.HasOne("MessengerAPI.Domain.UserAggregate.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessengerAPI.Domain.UserAggregate.User", b =>
                {
                    b.OwnsMany("MessengerAPI.Domain.UserAggregate.ValueObjects.Email", "Emails", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("AddedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPublic")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("Data")
                                .IsUnique();

                            b1.HasIndex("UserId");

                            b1.ToTable("Email");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("MessengerAPI.Domain.UserAggregate.ValueObjects.Phone", "Phones", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("AddedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("Data")
                                .IsUnique();

                            b1.HasIndex("UserId");

                            b1.ToTable("Phone");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Emails");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("MessengerAPI.Domain.ChannelAggregate.Channel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MessengerAPI.Domain.Common.Entities.ReactionGroup", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("MessengerAPI.Domain.UserAggregate.User", b =>
                {
                    b.Navigation("ProfilePhotos");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
